### ISSUE TITLE
How can I fully uninstall it and install again...

### ISSUE THREAD

**Issue by OrionRandD** [joshpetit/BibleHubScrapper#15]
I am getting these errors:
How can I fully uninstall it and install again.
I am getting these errors:

biblehub find Matthew 2:4

Traceback (most recent call last):
  File "/home/vagner/.local/bin/biblehub", line 6, in <module>
    from biblehub import get_versions, find_verse, search, styling, parse_str, find_passage
  File "/home/vagner/.local/lib/python3.10/site-packages/biblehub/__init__.py", line 1, in <module>
    from biblehub.scrape_verses import find_verse, get_versions
  File "/home/vagner/.local/lib/python3.10/site-packages/biblehub/scrape_verses.py", line 1, in <module>
    import requests
  File "/home/vagner/.local/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/home/vagner/.local/lib/python3.10/site-packages/requests/utils.py", line 29, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/vagner/.local/lib/python3.10/site-packages/requests/cookies.py", line 174, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

-----------------------------

It is installed, though
$ which biblehub
/home/vagner/.local/bin/biblehub

**Comment by joshpetit** [comment]
Hm,try doing 
```
pip install --upgrade --force-reinstall biblehub
```

**Comment by OrionRandD** [comment]
> Hm,try doing
> 
> ```
> pip install --upgrade --force-reinstall biblehub
> ```
before doing that, I've found that biblehub here is installed in system-wide way.
and I can run it with, say:
sudo biblehub find matthew 23:1
But, if I run it as a normal user, 
it does not work...
Then I created an group called biblehub and added myself to it,
but it refuses to work as a normal user...

ll /usr/local/bin/biblehub
-rwxr-xr-x 1 root biblehub 5.2K Sep 10 19:18 /usr/local/bin/biblehub*

and

 ll /home/vagner/.local/lib/python3.10/site-packages/bin/biblehub
-rwxr-xr-x 1 vagner biblehub 174 Sep 10 19:00 /home/vagner/.local/lib/python3.10/site-packages/bin/biblehub*

I think I have to clean up all traces of biblehub in 

/usr/local/lib/python3.10/dist-packages/biblehub-2.0.1.dist-info/
and
/usr/local/lib/python3.10/dist-packages/biblehub/

I did that once, but I used "rm -fr" and installed it as as normal use with pip3,
Then the files were place in:
/home/vagner/.local/lib/python3.10/site-packages/bin/biblehub
But, I had that error up there again...
Is there a pip or pip3 command to purge biblehub completely, from system-wide and also from a user installation and then issue the command you just asked me?
thx

**Comment by joshpetit** [comment]
Hm. One thing I would always recommend is never trying to manually do package management, that will always cause problems haha. If you want to uninstall something you installed with sudo, you would do `sudo pip uninstall $PACKAGE_NAME`.

I'm not really sure what you could to fix this. If the biblehub executable is not on your path, you could try to just install it for the user then it'll have the same affect
